plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/richardburns/react/github/SDC445_Interface_Design_II/burns-netlify-app/build"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/Users/richardburns/react/github/SDC445_Interface_Design_II/burns-netlify-app"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]